<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="SuRaj" failures="1" tests="2" name="test.Login_withDataProvider_validation" time="16.629" errors="0" timestamp="2023-01-23T17:10:49 IST" skipped="0">
  <testcase classname="test.Login_withDataProvider_validation" name="CheckLogin" time="7.900"/>
  <system-out/>
  <testcase classname="test.Login_withDataProvider_validation" name="CheckLogin" time="8.729">
    <failure message="expected [Error: There is no user record corresponding to this identifier. The user may have been deleted.] but found []" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [Error: There is no user record corresponding to this identifier. The user may have been deleted.] but found []
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at test.Login_withDataProvider_validation.CheckLogin(Login_withDataProvider_validation.java:29)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
    </failure>
  </testcase> <!-- CheckLogin -->
  <system-out/>
</testsuite> <!-- test.Login_withDataProvider_validation -->
